//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18444
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace YurikoCS
{
	public interface CommandSender {

		string GetName();

		void SendMessage(string message);

		bool HasPermission(string node);
	}
}

